#!/bin/bash
shopt -s nocasematch

if [[ $# == 0 ]];
then
    echo "Presuming start"
    sudo systemctl start lighttpd
fi
if [[ $1 == "start" ]];
then
    echo "Presuming start"
    sudo systemctl start lighttpd
fi
if [[ $1 == "stop" ]];
then
	echo "Stopping webserver"
	sudo systemctl stop lighttpd
fi

echo "Done."
