#!/bin/bash
SRV="192.168.0.6"
USER="user" #User to mount as
LROOT="/mnt/sshfs" #Root location locally
RDIRS="/home/user /home/http" #Each directory
PERM="777"
for dir in $RDIRS
do
 LOCAL=$LROOT$dir
 echo "Creating $LOCAL"
 mkdir -p $LOCAL &>/dev/null
 echo "Unmounting if it is already mounted."
 sudo umount $LOCAL &>/dev/null
 echo "Connecting to REMOTE:$dir"
 sudo chmod $PERM $LOCAL
 sshfs $USER@$SRV:$dir $LOCAL
 #Make it ok for users to open
 if [[ $? != 0 ]]; then
  echo "Connection failed for some reason :("
  exit 1
 fi
done
