#!/bin/bash
if [[ $# < 1 ]]; then
	echo "Not enough arguments. See -h"
	exit 0
fi

if [[ $1 == "-h" || $1 == "--help" ]]; then
	echo "All you need is a flac file path. Literally just that."
	exit 0
fi

FILE=$1

flac -d $1 --force-raw-format --endian=little --sign=signed -c | aplay -f cd -
