#!/bin/bash
TEST=""
if [ $# -lt 2 ]
then
	echo "Not enough arguments supplied"
	exit 0
fi

if [[ $1 == "-h" ]]
then
	echo "Help:"
	echo "Argument 1: Input File"
	echo "Argument 2: Output File"
	echo "Add -t for testing a 15 second clip."
	exit 0
fi

if [[ $3 == "-t" ]]
then
	TEST="-ss 00:00:00 -to 00:00:15"
fi

ffmpeg -i $1 -strict -2 -aq 2 -acodec libmp3lame -vcodec libx264 $TEST $2

